apiVersion: v1
kind: Service
metadata: 
  name: kubeservive58070
spec:
  selector: 
    app: kubeusers58070
  ports: 
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kubedeploy
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: kubeusers58070
  template: 
    metadata: 
      labels: 
        app: kubeusers58070
    spec: 
      containers:
      - name: kubecontainer
        image: defe014/usercreator58070:1.0.0
        ports:
          - containerPort: 8080
        env: 
          - name: MONGO_URL
            value: mongodb+srv://Federico:Federico1@coderexample.hjzrdtr.mongodb.net/docker?retryWrites=true&w=majority
        imagePullPolicy: Always